set echo on;  
set serveroutput on;

DROP TABLE EMPIRE_WEBHOOKS;
DROP TABLE WEBHOOK;
DROP TABLE TEAMS;
DROP TABLE CHARACTER_TAGS;
DROP TABLE TAGS;
DROP TABLE MEMBER_CHARACTER;
DROP TABLE CHARACTERS;
DROP TABLE MEMBER;
DROP TABLE GUILD;


CREATE TABLE GUILD(
	GUILD_ID INTEGER PRIMARY KEY,
	NAME VARCHAR(50),
	URL VARCHAR(200),
    COLOR int,
	PROFILE_COUNT INTEGER,
	MEMBER_COUNT INTEGER,
	GALACTIC_POWER INTEGER,
	LASTSYNC  DATETIME
);

INSERT INTO GUILD (GUILD_ID, NAME, COLOR) VALUES (25666,'Chimaera',16007746);
INSERT INTO GUILD (GUILD_ID, NAME, COLOR) VALUES (26170,'Devastator',0);
INSERT INTO GUILD (GUILD_ID, NAME, COLOR) VALUES (26453,'Eclipse',0);
INSERT INTO GUILD (GUILD_ID, NAME, COLOR) VALUES (44009,'Executor',0);
INSERT INTO GUILD (GUILD_ID, NAME, COLOR) VALUES (33287,'Nemesis',0);
INSERT INTO GUILD (GUILD_ID, NAME, COLOR) VALUES (15981,'Perilous',0);
INSERT INTO GUILD (GUILD_ID, NAME, COLOR) VALUES (5973,'Predator',0);
INSERT INTO GUILD (GUILD_ID, NAME, COLOR) VALUES (26040,'Ravager',65280);
INSERT INTO GUILD (GUILD_ID, NAME, COLOR) VALUES (26384,'Reaper',12632256);
INSERT INTO GUILD (GUILD_ID, NAME, COLOR) VALUES (36289,'Vanguard',65535);
INSERT INTO GUILD (GUILD_ID, NAME, COLOR) VALUES (35846,'Vengeance',8421568);

CREATE TABLE MEMBER (
	MEMBER_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(50),	
	GUILD_ID INTEGER,
	PROFILE VARCHAR(200),
	ALLYCODE VARCHAR(11),
	DISCORD VARCHAR(200),
	URL VARCHAR(150),
	LASTSYNC_GG DATETIME,
	LASTSYNC DATETIME,
	LEVEL INTEGER,
	GALACTIC_POWER INTEGER,
	SHIP_GALACTIC_POWER INTEGER,
	CHARACTER_GALACTIC_POWER INTEGER,
	FOREIGN KEY (GUILD_ID) REFERENCES GUILD(GUILD_ID) ON DELETE CASCADE
);

CREATE TABLE CHARACTERS(
	CHARACTER_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(50),
	BASE_ID VARCHAR(50),
	POWER INTEGER,
	URL VARCHAR(150),
	IMAGE_URL VARCHAR(150),
	DESCRIPTION VARCHAR(150)
);

CREATE TABLE MEMBER_CHARACTER(
	MEMBER_ID INTEGER NOT NULL,
	CHARACTER_ID INTEGER NOT NULL,
	STAR INTEGER,
	GEAR INTEGER,
	GALACTIC_POWER INTEGER,
	GALACTIC_POWER_MAX INTEGER,

	PRIMARY KEY(MEMBER_ID, CHARACTER_ID),
	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,
	FOREIGN KEY (CHARACTER_ID) REFERENCES CHARACTERS(CHARACTER_ID) ON DELETE CASCADE
);

CREATE TABLE TAGS(
	TAG_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TAG_NAME VARCHAR(50)
);

CREATE TABLE CHARACTER_TAGS(
	CHARTAG_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TAG_ID INTEGER,
	CHARACTER_ID INTEGER,

	FOREIGN KEY (TAG_ID) REFERENCES TAGS(TAG_ID) ON DELETE CASCADE,
	FOREIGN KEY (CHARACTER_ID) REFERENCES CHARACTERS(CHARACTER_ID) ON DELETE CASCADE

);

CREATE TABLE TEAMS(
	TEAM_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	LEADER_ID INTEGER,
	CHARACTER2_ID INTEGER,
	CHARACTER3_ID INTEGER,
	CHARACTER4_ID INTEGER,
	CHARACTER5_ID INTEGER,
	CALLED INTEGER DEFAULT 0,
	FOREIGN KEY (LEADER_ID) REFERENCES CHARACTERS(CHARACTER_ID) ON DELETE CASCADE,
	FOREIGN KEY (CHARACTER2_ID) REFERENCES CHARACTERS(CHARACTER_ID) ON DELETE CASCADE,
	FOREIGN KEY (CHARACTER3_ID) REFERENCES CHARACTERS(CHARACTER_ID) ON DELETE CASCADE,
	FOREIGN KEY (CHARACTER4_ID) REFERENCES CHARACTERS(CHARACTER_ID) ON DELETE CASCADE,
	FOREIGN KEY (CHARACTER5_ID) REFERENCES CHARACTERS(CHARACTER_ID) ON DELETE CASCADE
);

CREATE TABLE WEBHOOK(
	WEBHOOK_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	WEBHOOK_TYPE VARCHAR(50)
);

INSERT INTO WEBHOOK (WEBHOOK_TYPE) VALUES ('TB');
INSERT INTO WEBHOOK (WEBHOOK_TYPE) VALUES ('TW');
INSERT INTO WEBHOOK (WEBHOOK_TYPE) VALUES ('Raid');

CREATE TABLE EMPIRE_WEBHOOKS(
    EMPHOOK_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    GUILD_ID INTEGER,
    WEBHOOK_ID INTEGER,
    WEBHOOK_URL VARCHAR(100),

	FOREIGN KEY (GUILD_ID) REFERENCES GUILD(GUILD_ID) ON DELETE CASCADE,
	FOREIGN KEY (WEBHOOK_ID) REFERENCES WEBHOOK(WEBHOOK_ID) ON DELETE CASCADE
);

INSERT INTO EMPIRE_WEBHOOKS (GUILD_ID, WEBHOOK_ID, WEBHOOK_URL) VALUES (44009,1,'https://discordapp.com/api/webhooks/481263923262128148/tJxH-3cxNDamcLPMKC_yGMXS0ILHP8ssIqrXqur4PlOEix2vJCVEJQSI13QgLwBK4LjY');
INSERT INTO EMPIRE_WEBHOOKS (GUILD_ID, WEBHOOK_ID, WEBHOOK_URL) VALUES (26040,1,'https://discordapp.com/api/webhooks/478579983028322304/96t8ant1OLb0b_ER98K-ty4x5QSR48j0u6CqmRInu0vahF_ZGljytTdGjnjdZgc6U7qj');
INSERT INTO EMPIRE_WEBHOOKS (GUILD_ID, WEBHOOK_ID, WEBHOOK_URL) VALUES (26384,1,'https://discordapp.com/api/webhooks/485131110599098369/7jU_GtFWyQrVduj8rbYWWnRVkg_IQKR821MkU__JKs3m8A9htvhu8ukn-WuucSgoBYC9');
INSERT INTO EMPIRE_WEBHOOKS (GUILD_ID, WEBHOOK_ID, WEBHOOK_URL) VALUES (36289,1,'https://discordapp.com/api/webhooks/383281809678401538/ugGpx5Ii4EROKKM-4pu2qYk-tHIWJx_TjLdcYFVOyzxdGme4naYZUylIUl-VZ0m_JAqr');

DROP PROCEDURE IF EXISTS USP_GUILDLIST;

CREATE PROCEDURE USP_GUILDLIST() NOT DETERMINISTIC READS SQL DATA SQL SECURITY DEFINER SELECT GUILD_ID, NAME FROM GUILD WHERE 1 order by NAME

CALL usp_GuildList();