set echo on;  
set serveroutput on;

DROP TABLE GUILD CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE CHARACTER CASCADE CONSTRAINTS;
DROP TABLE MEMBER_CHARACTER CASCADE CONSTRAINTS;
DROP TABLE TAGS CASCADE CONSTRAINTS;
DROP TABLE CHARACTER_TAGS CASCADE CONSTRAINTS;
DROP TABLE TEAMS CASCADE CONSTRAINTS;
DROP TABLE WEBHOOK CASCADE CONSTRAINTS;
DROP TABLE EMPIRE_WEBHOOKS CASCADE CONSTRAINTS;

CREATE TABLE GUILD(
	GUILD_ID INTEGER PRIMARY KEY,
	NAME VARCHAR(50),
	URL VARCHAR(200),
    COLOR int,
	PROFILE_COUNT INTEGER,
	MEMBER_COUNT INTEGER,
	GALACTIC_POWER INTEGER
	LASTSYNC  DATETIME
);

INSERT INTO GUILD (GUILD_ID, NAME, COLOR) VALUES (25666,'Chimaera',16007746);
INSERT INTO GUILD (GUILD_ID, NAME, COLOR) VALUES (26170,'Devastator',0);
INSERT INTO GUILD (GUILD_ID, NAME, COLOR) VALUES (26453,'Eclipse',0);
INSERT INTO GUILD (GUILD_ID, NAME, COLOR) VALUES (44009,'Executor',0);
INSERT INTO GUILD (GUILD_ID, NAME, COLOR) VALUES (33287,'Nemesis',0);
INSERT INTO GUILD (GUILD_ID, NAME, COLOR) VALUES (15981,'Perilous',0);
INSERT INTO GUILD (GUILD_ID, NAME, COLOR) VALUES (5973,'Predator',0);
INSERT INTO GUILD (GUILD_ID, NAME, COLOR) VALUES (26040,'Ravager',65280);
INSERT INTO GUILD (GUILD_ID, NAME, COLOR) VALUES (26384,'Reaper',12632256);
INSERT INTO GUILD (GUILD_ID, NAME, COLOR) VALUES (36289,'Vanguard',65535);
INSERT INTO GUILD (GUILD_ID, NAME, COLOR) VALUES (35846,'Vengeance',8421568);

CREATE TABLE PLAYER (
	MEMBER_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(50),	
	GUILD_ID INTEGER,
	PROFILE VARCHAR(200),
	ALLYCODE VARCHAR(11),
	DISCORD VARCHAR(200),
	URL VARCHAR(150),
	LASTSYNC_GG DATETIME,
	LASTSYNC DATETIME,
	LEVEL INTEGER,
	GALACTIC_POWER INTEGER,
	SHIP_GALACTIC_POWER INTEGER,
	CHARACTER_GALACTIC_POWER INTEGER,
	FOREIGN KEY (GUILD_ID) REFERENCES GUILD(GUILD_ID)
);

CREATE TABLE CHARACTER(
	CHARACTER_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(50),
	BASE_ID VARCHAR(50),
	POWER INTEGER,
	URL VARCHAR(150),
	IMAGE_URL VARCHAR(150),
	DESCRIPTION VARCHAR(150)
);

CREATE TABLE TAGS(
	TAG_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TAG_NAME NAME VARCHAR(50)
);

CREATE TABLE CHARACTER_TAGS(
	CHARTAG_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TAG_ID VARCHAR(50),
	CHARACTER_ID VARCHAR(50),

	FOREIGN KEY (TAG_ID) REFERENCES TAGS(TAG_ID),
	FOREIGN KEY (CHARACTER_ID) REFERENCES CHARACTER(CHARACTER_ID),

);

CREATE TABLE MEMBER_CHARACTER(
	MEMBER_ID INTEGER NOT NULL,
	CHARACTER_ID INTEGER NOT NULL,
	STAR INTEGER,
	GEAR INTEGER,
	GALACTIC_POWER INTEGER,
	GALACTIC_POWER_MAX INTEGER,

	PRIMARY KEY(MEMBER_ID, CHARACTER_ID),
	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
	FOREIGN KEY (CHARACTER_ID) REFERENCES CHARACTER(CHARACTER_ID)
);

CREATE TABLE TEAMS(
	TEAM_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	LEADER_ID INTEGER,
	CHARACTER2_ID INTEGER,
	CHARACTER3_ID INTEGER,
	CHARACTER4_ID INTEGER,
	CHARACTER5_ID INTEGER,
	CALLED INTEGER DEFAULT 0,
	FOREIGN KEY (LEADER_ID) REFERENCES CHARACTER(CHARACTER_ID),
	FOREIGN KEY (CHARACTER2_ID) REFERENCES CHARACTER(CHARACTER_ID),
	FOREIGN KEY (CHARACTER3_ID) REFERENCES CHARACTER(CHARACTER_ID),
	FOREIGN KEY (CHARACTER4_ID) REFERENCES CHARACTER(CHARACTER_ID),
	FOREIGN KEY (CHARACTER5_ID) REFERENCES CHARACTER(CHARACTER_ID)
);

CREATE TABLE WEBHOOK(
	WEBHOOK_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	WEBHOOK_TYPE VARCHAR(50)
);

INSERT INTO WEBHOOK (WEBHOOK_TYPE) VALUES ('TB');
INSERT INTO WEBHOOK (WEBHOOK_TYPE) VALUES ('TW');
INSERT INTO WEBHOOK (WEBHOOK_TYPE) VALUES ('Raid');

CREATE TABLE EMPIRE_WEBHOOKS(
    EMPHOOK_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    GUILD_ID INTEGER,
    WEBHOOK_ID INTEGER,
    WEBHOOK_URL VARCHAR(100),

	FOREIGN KEY (GUILD_ID) REFERENCES GUILD(GUILD_ID),
	FOREIGN KEY (WEBHOOK_ID) REFERENCES WEBHOOK(WEBHOOK_ID)
);

INSERT INTO EMPIRE_WEBHOOKS (GUILD_ID, WEBHOOK_ID, WEBHOOK_URL) VALUES (44009,1,'https://discordapp.com/api/webhooks/481263923262128148/tJxH-3cxNDamcLPMKC_yGMXS0ILHP8ssIqrXqur4PlOEix2vJCVEJQSI13QgLwBK4LjY');
INSERT INTO EMPIRE_WEBHOOKS (GUILD_ID, WEBHOOK_ID, WEBHOOK_URL) VALUES (26040,1,'https://discordapp.com/api/webhooks/478579983028322304/96t8ant1OLb0b_ER98K-ty4x5QSR48j0u6CqmRInu0vahF_ZGljytTdGjnjdZgc6U7qj');
INSERT INTO EMPIRE_WEBHOOKS (GUILD_ID, WEBHOOK_ID, WEBHOOK_URL) VALUES (26384,1,'https://discordapp.com/api/webhooks/485131110599098369/7jU_GtFWyQrVduj8rbYWWnRVkg_IQKR821MkU__JKs3m8A9htvhu8ukn-WuucSgoBYC9');
INSERT INTO EMPIRE_WEBHOOKS (GUILD_ID, WEBHOOK_ID, WEBHOOK_URL) VALUES (36289,1,'https://discordapp.com/api/webhooks/383281809678401538/ugGpx5Ii4EROKKM-4pu2qYk-tHIWJx_TjLdcYFVOyzxdGme4naYZUylIUl-VZ0m_JAqr');

DROP PROCEDURE IF EXISTS USP_GUILDLIST;

CREATE PROCEDURE USP_GUILDLIST() NOT DETERMINISTIC READS SQL DATA SQL SECURITY DEFINER SELECT GUILD_ID, NAME FROM GUILD WHERE 1 order by NAME

CALL usp_GuildList();

/* Not neccessary

from MEMBER

	STERILE_NAME VARCHAR(50),

CREATE TABLE MEMBERGUILD(
	MEMBERGUILD_ID INTEGER PRIMARY KEY,
	MEMBER_ID INTEGER,
	GUILD_ID INTEGER,
	LASTSYNC_GG DATE,
	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
	FOREIGN KEY (GUILD_ID) REFERENCES GUILD(GUILD_ID)
);


CREATE TABLE MEMBERTOONS(
	MEMTOONS_ID INTEGER PRIMARY KEY,
	MEMBER_ID INTEGER,
	TOON_ID INTEGER,
	STAR INTEGER,
	GEAR INTEGER,
	GALACTIC_POWER INTEGER,
	GALACTIC_POWER_MAX INTEGER,
	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
	FOREIGN KEY (TOON_ID) REFERENCES TOON(TOON_ID)
);
*/
/*


CREATE TABLE TEAMS(
	TEAM_ID INTEGER PRIMARY KEY,
	LEADER_ID INTEGER,
	LEADER_STARS INTEGER,
	LEADER_GEAR	INTEGER,
	LEADER_LEVEL INTEGER,
	TOON2_ID INTEGER,
	TOON2_STARS INTEGER,
	TOON2_GEAR	INTEGER,
	TOON2_LEVEL INTEGER,
	TOON3_ID INTEGER,
	TOON3_STARS INTEGER,
	TOON3_GEAR	INTEGER,
	TOON3_LEVEL INTEGER,
	TOON4_ID INTEGER,
	TOON4_STARS INTEGER,
	TOON4_GEAR	INTEGER,
	TOON4_LEVEL INTEGER,
	TOON5_ID INTEGER,
	TOON5_STARS INTEGER,
	TOON5_GEAR	INTEGER,
	TOON5_LEVEL INTEGER,
	CALLED INTEGER DEFAULT 0,
	FOREIGN KEY (LEADER_ID) REFERENCES TOON(TOON_ID),
	FOREIGN KEY (TOON2_ID) REFERENCES TOON(TOON_ID),
	FOREIGN KEY (TOON3_ID) REFERENCES TOON(TOON_ID),
	FOREIGN KEY (TOON4_ID) REFERENCES TOON(TOON_ID),
	FOREIGN KEY (TOON5_ID) REFERENCES TOON(TOON_ID)
);

	CLASS_CODE		NUMBER (5, 0) NOT NULL,
	STU_NUM			INTEGER NOT NULL,
	ENROLL_GRADE	CHAR(1),
	FOREIGN KEY (STU_NUM) REFERENCES STUDENT(STU_NUM),
	PRIMARY KEY(CLASS_CODE, STU_NUM)

	*/