set echo on;  
set serveroutput on;

DROP TABLE GUILD CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE TOON CASCADE CONSTRAINTS;
DROP TABLE MEMBERTOONS CASCADE CONSTRAINTS;
DROP TABLE TEAMS CASCADE CONSTRAINTS;

CREATE TABLE GUILD(
	GUILD_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(50),	
	PROFILE VARCHAR(200),
	LASTSYNC  DATETIME
);

CREATE TABLE MEMBER (
	MEMBER_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(50),	
	GUILD_ID INTEGER,
	PROFILE VARCHAR(200),
	ALLYCODE VARCHAR(11),
	DISCORD VARCHAR(200),
	LASTSYNC_GG DATETIME,
	LASTSYNC DATETIME,
	LEVEL INTEGER,
	GALACTIC_POWER INTEGER,
	FOREIGN KEY (GUILD_ID) REFERENCES GUILD(GUILD_ID)
);

CREATE TABLE TOON(
	TOON_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(150)
);

CREATE TABLE MEMBERTOONS(
	MEMBER_ID INTEGER NOT NULL,
	TOON_ID INTEGER NOT NULL,
	STAR INTEGER,
	GEAR INTEGER,
	GALACTIC_POWER INTEGER,
	GALACTIC_POWER_MAX INTEGER,

	PRIMARY KEY(MEMBER_ID, TOON_ID),
	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
	FOREIGN KEY (TOON_ID) REFERENCES TOON(TOON_ID)
);

CREATE TABLE TEAMS(
	TEAM_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	LEADER_ID INTEGER,
	TOON2_ID INTEGER,
	TOON3_ID INTEGER,
	TOON4_ID INTEGER,
	TOON5_ID INTEGER,
	CALLED INTEGER DEFAULT 0,
	FOREIGN KEY (LEADER_ID) REFERENCES TOON(TOON_ID),
	FOREIGN KEY (TOON2_ID) REFERENCES TOON(TOON_ID),
	FOREIGN KEY (TOON3_ID) REFERENCES TOON(TOON_ID),
	FOREIGN KEY (TOON4_ID) REFERENCES TOON(TOON_ID),
	FOREIGN KEY (TOON5_ID) REFERENCES TOON(TOON_ID)
);


/* Not neccessary

from MEMBER

	STERILE_NAME VARCHAR(50),

CREATE TABLE MEMBERGUILD(
	MEMBERGUILD_ID INTEGER PRIMARY KEY,
	MEMBER_ID INTEGER,
	GUILD_ID INTEGER,
	LASTSYNC_GG DATE,
	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
	FOREIGN KEY (GUILD_ID) REFERENCES GUILD(GUILD_ID)
);


CREATE TABLE MEMBERTOONS(
	MEMTOONS_ID INTEGER PRIMARY KEY,
	MEMBER_ID INTEGER,
	TOON_ID INTEGER,
	STAR INTEGER,
	GEAR INTEGER,
	GALACTIC_POWER INTEGER,
	GALACTIC_POWER_MAX INTEGER,
	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
	FOREIGN KEY (TOON_ID) REFERENCES TOON(TOON_ID)
);
*/
/*


CREATE TABLE TEAMS(
	TEAM_ID INTEGER PRIMARY KEY,
	LEADER_ID INTEGER,
	LEADER_STARS INTEGER,
	LEADER_GEAR	INTEGER,
	LEADER_LEVEL INTEGER,
	TOON2_ID INTEGER,
	TOON2_STARS INTEGER,
	TOON2_GEAR	INTEGER,
	TOON2_LEVEL INTEGER,
	TOON3_ID INTEGER,
	TOON3_STARS INTEGER,
	TOON3_GEAR	INTEGER,
	TOON3_LEVEL INTEGER,
	TOON4_ID INTEGER,
	TOON4_STARS INTEGER,
	TOON4_GEAR	INTEGER,
	TOON4_LEVEL INTEGER,
	TOON5_ID INTEGER,
	TOON5_STARS INTEGER,
	TOON5_GEAR	INTEGER,
	TOON5_LEVEL INTEGER,
	CALLED INTEGER DEFAULT 0,
	FOREIGN KEY (LEADER_ID) REFERENCES TOON(TOON_ID),
	FOREIGN KEY (TOON2_ID) REFERENCES TOON(TOON_ID),
	FOREIGN KEY (TOON3_ID) REFERENCES TOON(TOON_ID),
	FOREIGN KEY (TOON4_ID) REFERENCES TOON(TOON_ID),
	FOREIGN KEY (TOON5_ID) REFERENCES TOON(TOON_ID)
);

	CLASS_CODE		NUMBER (5, 0) NOT NULL,
	STU_NUM			INTEGER NOT NULL,
	ENROLL_GRADE	CHAR(1),
	FOREIGN KEY (STU_NUM) REFERENCES STUDENT(STU_NUM),
	PRIMARY KEY(CLASS_CODE, STU_NUM)

	*/